spring:
  datasource:
    url: jdbc:mysql://localhost/chatdemo?useLegacyDatetimeCode=false&serverTimezone=Europe/Minsk&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create

---

chatdemo:
  dictionary-path: d:/Projects/idea/chat-bot/src/main/big-files/glove.6B.100d.txt
  movie-lines: d:/Projects/idea/chat-bot/src/main/resources/movie_lines.txt
  movie-conversations: d:/Projects/idea/chat-bot/src/main/resources/movie_conversations.txt
  
